id: '1aaf4e89-d95f-402f-7390-08dd7ccec69f'
name: 'C3-X-DB-FI'
description: 'This is my eLearning Project with the Databricks Stage File generator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.Stage.Spark.Databricks.File'
  version: '1.8.0'
sourceSystems:
  - id: '82095b99-600c-422a-a5c1-5f5492c10e69'
    name: 'ADW'
    description: 'begenius discovery - file'
    activeDiscovery: '153bf2d9-0087-4621-bd7d-364f8803abfb'
    sourceSystemTypeId: 'c5e55725-184f-4c60-a22d-70cb5d6fe513'
  - id: 'a113d9bc-e379-44d2-907c-5f2efb66de3c'
    name: 'CRM'
    description: ''
    sourceSystemTypeId: 'c5e55725-184f-4c60-a22d-70cb5d6fe513'
propertyValues:
  - propertyId: '59eca19a-3bec-4169-85fd-41331f6fac3a'
    value: 'true'
  - propertyId: 'a9de64e6-8417-4f17-b491-4f105ed891a9'
    value: 'Sequential Notebook'
